### ISSUE TITLE
SVN repo not accessible

### ISSUE THREAD

**Issue by siddhya** [davidmball/ratslam#10]
I want to try out the RatSLAM C++ Library code. But the svn path mentioned in the C++ README.md is not working.

$ svn checkout http://ratslam.googlecode.com/svn/trunk/ ratslam-read-only
svn: E170013: Unable to connect to a repository at URL 'http://ratslam.googlecode.com/svn/trunk'
svn: E160013: '/svn/trunk' path not found

**Comment by davidmball** [comment]
Are you referring to the stand alone C++ library or the ROS C++ version? I don't know how well the C++ version will work now. You can get the ROS version as per the instructions here: 
https://github.com/davidmball/ratslam/blob/wiki/RatSLAMROS.md

The svn command won't work anymore as the repository is now a git repository.

**Comment by siddhya** [comment]
Ok Thanks. I was looking for the C++ library since I do not use ROS.

**Comment by davidmball** [comment]
Note that they both use the same core library. ie the ROS version is basically a thin ROS wrapper around the ratslam C++ library. 
The C++ only version is a bit behind the ROS version. However, if you want to use it then you should check out the master branch using git.
