### ISSUE TITLE
How to run openratslam with usb camera

### ISSUE THREAD

**Issue by sunt40** [davidmball/ratslam#12]
Hello Dr ball,I want to know how to run your code with usb camera.I want to map indoor environment.Could you help me  ?

**Comment by scott--** [comment]
Have a look here https://github.com/davidmball/ratslam/blob/wiki/RatSLAMROS.md at "Using Custom Bag Files (or Real Robots)"

You will probably also need something like this for a USB camera. https://github.com/ros-drivers/libuvc_ros

**Comment by sunt40** [comment]
@scott-- I have written my own config file and launch file.For example,I(or a robot) take my laptop and move around the room,how to use the openratslam  to generate a map?

**Comment by scott--** [comment]
Once you run OpenRatSLAM, you need another node to publish JPEG images on:
`/<topic_root>/camera/image/compressed`
where <topic_root> matches the 'topic_root' in the config file.

I think that you can use libuvc_ros for that, but I have not used it myself, so I can't help you with that.

You can also have a look at the provided datasets here (https://wiki.qut.edu.au/display/cyphy/OpenRatSLAM+datasets) if you just want to see an example of OpenRatSLAM working.

**Comment by sunt40** [comment]
@scott-- OK.Thanks for your patience.
