### ISSUE TITLE
Missing datasets?

### ISSUE THREAD

**Issue by chrisspen** [davidmball/ratslam#23]
The [ROS build instructions](https://github.com/davidmball/ratslam/blob/wiki/RatSLAMROS.md), under the "Running RatSLAM" section, link to datasets at https://wiki.qut.edu.au/display/cyphy/OpenRatSLAM+datasets, but this link is broken, and just redirects to a login page.

Are these datasets still available? If so, where can we find them?

**Comment by xlong0513** [comment]
Hi, there. did u fix the problem now?

**Comment by lukvacek** [comment]
Looks like you can still access the page archive.org: https://web.archive.org/web/20190407200207/https://wiki.qut.edu.au/display/cyphy/openRatSLAM+datasets

When clicking on each of the rosbag links available on that site, copy the link first, delete the archive.org url portion and then past the rest into your browser for download.

**Comment by bessszilard** [comment]
For me this link worked: https://wiki.qut.edu.au/display/raq/OpenRatSLAM+datasets

**Comment by raysworld** [comment]
> Looks like you can still access the page archive.org: https://web.archive.org/web/20190407200207/https://wiki.qut.edu.au/display/cyphy/openRatSLAM+datasets
> 
> When clicking on each of the rosbag links available on that site, copy the link first, delete the archive.org url portion and then past the rest into your browser for download.

Following the archive.org's page I could find the links to the bag files:

 - iRat 2011 Australia
The iRat - intelligent Rat animat technology
https://mega.nz/file/FAlXyZbB#6rMpQ6EE4LQIKmZvy5zN7Stdu4pIzZm2h3TnHkG2wms

 - St Lucia 2007
The dataset for the ROS version of openRatSLAM is available at (in multipart zip).
https://mega.nz/file/od8xVbKJ#E81hKj-M1-CybBkX1dLe3htAJw-gP9MAQIEeZkPwuUY

 - Oxford's New College (2008)
We have re-encoded Oxford's dataset into a rosbag file. The rosbag file only include the odometry and the panoramic image sensor data. The odometry has been integrated to be at the same rate (3Hz) as the panoramic images. Note that this re-encoded datset file has been created without permission and is maintained purely by us.
https://mega.nz/#!oJdwxTAJ!EB-M_gLWq8Sy2uFvmER-D_uTZ7_Rd4v-5ZUhu1YGNCQ

If you use this dataset, please reference the original paper:
> Mike Smith, Ian Baldwin, Winston Churchill, Rohan Paul, Paul Newman (2009) The New College Vision and Laser Data Set. The International Journal of Robotics Research. 28:5

**Comment by davidmball** [comment]
Thank you for providing the links. I've updated the home page (https://github.com/davidmball/ratslam) with links to the datasets.
