### ISSUE TITLE
ROS example not working on Melodic

### ISSUE THREAD

**Issue by chrisspen** [davidmball/ratslam#24]
I'm trying to test RatSLAM using my laptop's camera on Melodic/Ubuntu 18. I followed your [ROS](https://github.com/davidmball/ratslam/blob/wiki/RatSLAMROS.md) instructions and created my own config file and launch file, which looks like:

    <launch>

        <machine name="local_alt" address="localhost" default="true" />

        <node name="camera" pkg="usb_cam" type="usb_cam_node" output="screen" >
            <param name="video_device" value="/dev/video0" />
            <param name="image_width" value="640" />
            <param name="image_height" value="480" />
            <param name="pixel_format" value="yuyv" />
            <param name="camera_frame_id" value="camera" />
            <param name="io_method" value="mmap"/>
        </node>
        
        <node name="camera_raw_to_plain" pkg="topic_tools" type="relay" output="screen" args="/camera/image_raw/compressed /camera/image/compressed" />
        
        <node name="rqt_image_view" pkg="rqt_image_view" type="rqt_image_view" output="screen">
            <param name="image" type="string" value="/camera/image" />
            <param name="image_transport" type="string" value="compressed" />
        </node>
        
        <node name="RatSLAMLocalViewCells" pkg="ratslam_ros" type="ratslam_lv" args="$(find ratslam_ros)/config/config_myrobot.txt _image_transport:=compressed" cwd="node" required="true" />
        <node name="RatSLAMPoseCells" pkg="ratslam_ros" type="ratslam_pc" args="$(find ratslam_ros)/config/config_myrobot.txt _image_transport:=compressed" cwd="node" required="true" />
        <node name="RatSLAMExperienceMap" pkg="ratslam_ros" type="ratslam_em" args="$(find ratslam_ros)/config/config_myrobot.txt _image_transport:=compressed" cwd="node" required="true" />
        <node name="RatSLAMVisualOdometry" pkg="ratslam_ros" type="ratslam_vo" args="$(find ratslam_ros)/config/config_myrobot.txt _image_transport:=compressed" cwd="node" required="true" />
        
        <node pkg="rqt_plot" type="rqt_plot" name="plot_vt_em" args="/myrobot/LocalView/Template/current_id,/myrobot/PoseCell/TopologicalAction/dest_id" />
        <node pkg="rosbag" type="record" name="record" args="/myrobot/ExperienceMap/Map /myrobot/ExperienceMap/RobotPose /myrobot/LocalView/Template /myrobot/PoseCell/TopologicalAction -O ratslam_out.bag" />

    </launch>

And when I run it with:

    roslaunch ratslam_ros myrobot.launch

I get the output:

    started roslaunch server http://myrobot:35681/

    SUMMARY
    ========

    PARAMETERS
     * /camera/camera_frame_id: camera
     * /camera/image_height: 480
     * /camera/image_width: 640
     * /camera/io_method: mmap
     * /camera/pixel_format: yuyv
     * /camera/video_device: /dev/video0
     * /rosdistro: melodic
     * /rosversion: 1.14.3
     * /rqt_image_view/image: /camera/image
     * /rqt_image_view/image_transport: compressed

    NODES
      /
        RatSLAMExperienceMap (ratslam_ros/ratslam_em)
        RatSLAMLocalViewCells (ratslam_ros/ratslam_lv)
        RatSLAMPoseCells (ratslam_ros/ratslam_pc)
        RatSLAMVisualOdometry (ratslam_ros/ratslam_vo)
        camera (usb_cam/usb_cam_node)
        camera_raw_to_plain (topic_tools/relay)
        plot_vt_em (rqt_plot/rqt_plot)
        record (rosbag/record)
        rqt_image_view (rqt_image_view/rqt_image_view)

    auto-starting new master
    process[master]: started with pid [8930]
    ROS_MASTER_URI=http://localhost:11311

    setting /run_id to e3787380-627a-11ea-a946-a86bad2a2295
    process[rosout-1]: started with pid [8941]
    started core service [/rosout]
    process[camera-2]: started with pid [8948]
    process[camera_raw_to_plain-3]: started with pid [8949]
    process[rqt_image_view-4]: started with pid [8950]
    process[RatSLAMLocalViewCells-5]: started with pid [8956]
    process[RatSLAMPoseCells-6]: started with pid [8962]
    process[RatSLAMExperienceMap-7]: started with pid [8963]
    process[RatSLAMVisualOdometry-8]: started with pid [8968]
    process[plot_vt_em-9]: started with pid [8975]
    process[record-10]: started with pid [8981]
    [ INFO] [1583809057.823398764]: using default calibration URL
    [ INFO] [1583809057.825558439]: camera calibration URL: file:///home/chris/.ros/camera_info/head_camera.yaml
    [ INFO] [1583809057.825767324]: Unable to open camera calibration file [/home/chris/.ros/camera_info/head_camera.yaml]
    [ WARN] [1583809057.825833158]: Camera calibration file /home/chris/.ros/camera_info/head_camera.yaml not found.
    [ INFO] [1583809057.825909833]: Starting 'head_camera' (/dev/video0) at 640x480 via mmap (yuyv) at 30 FPS
    [ WARN] [1583809058.032384062]: unknown control 'focus_auto'

    [ INFO] [1583809058.183207234]: advertised as /camera/image/compressed

    [plot_vt_em-9] process has died [pid 8975, exit code 1, cmd /opt/ros/melodic/lib/rqt_plot/rqt_plot /myrobot/LocalView/Template/current_id,/myrobot/PoseCell/TopologicalAction/dest_id __name:=plot_vt_em __log:=/home/chris/.ros/log/e3787380-627a-11ea-a946-a86bad2a2295/plot_vt_em-9.log].
    log file: /home/chris/.ros/log/e3787380-627a-11ea-a946-a86bad2a2295/plot_vt_em-9*.log

It looks like almost all nodes start correctly except for Rqt. The log reports the error:

    qt_gui_main() found no plugin matching "rqt_plot.plot.Plot"
    try passing the option "--force-discover"

Do you know what this means, and how I can fix it? Googling finds some similar errors, but no exact matches, and the proposed fixes have no effect.

**Comment by chrisspen** [comment]
Spoke too soon. Following [this](https://answers.ros.org/question/91231/rqt-plugin-not-listedfound-in-list-returned-by-rqt-list-plugins/?answer=91386?answer=91386#post-id-91386) post, I tried running:

    rm ~/.config/ros.org/rqt_gui.ini

to clear the Rqt cache, and that fixed it.

However, now I get five windows, an rqt_image_view window showing my camera feed, an empty rqt_plot window, and three blank black windows showing nothing, implying it's still not working. However, I'm not getting any errors.

Following your advice on [this issue](https://github.com/davidmball/ratslam/issues/14), I checked the output of `rosnode info /RatSLAMLocalViewCells` and it outputs:

    --------------------------------------------------------------------------------
    Node [/RatSLAMLocalViewCells]
    Publications: 
     * /RatSLAMLocalViewCells/compressed/parameter_descriptions [dynamic_reconfigure/ConfigDescription]
     * /RatSLAMLocalViewCells/compressed/parameter_updates [dynamic_reconfigure/Config]
     * /myrobot/LocalView/Template [ratslam_ros/ViewTemplate]
     * /rosout [rosgraph_msgs/Log]

    Subscriptions: 
     * /myrobot/camera/image/compressed [unknown type]

    Services: 
     * /RatSLAMLocalViewCells/compressed/set_parameters
     * /RatSLAMLocalViewCells/get_loggers
     * /RatSLAMLocalViewCells/set_logger_level


    contacting node http://myrobot:34979/ ...
    Pid: 10347
    Connections:
     * topic: /rosout
        * to: /rosout
        * direction: outbound
        * transport: TCPROS
     * topic: /myrobot/LocalView/Template
        * to: /RatSLAMPoseCells
        * direction: outbound
        * transport: TCPROS
     * topic: /myrobot/LocalView/Template
        * to: /record
        * direction: outbound
        * transport: TCPROS
     * topic: /myrobot/LocalView/Template
        * to: /plot_vt_em
        * direction: outbound
        * transport: TCPROS

implying the nodes are running.

What am I doing wrong?

**Comment by chrisspen** [comment]
The only concerning thing I see is:

     /myrobot/camera/image/compressed [unknown type]

Why is the RatSLAMLocalViewCells node unable to determine the type of the camera feed?

If I run `rostopic info /camera/image/compressed` it correctly shows `Type: sensor_msgs/CompressedImage`.

**Comment by chrisspen** [comment]
I think I've gotten it partially working. The part I'd gotten wrong was the "topic_root" value. In the [docs](https://github.com/davidmball/ratslam/blob/wiki/RatSLAMROS.md) you write to set this to the name of your robot, which matches the launch file name, and which I uniformly called "myrobot". However, this is incorrect, and is probably why so many people have trouble getting this to run.

The topic root needs to match the source of the video feed, not necessarily the robot, which you hinted at in issue #14. I was also using the usb_cam node, so in my config file I change my topic_root to "usb_cam" and like magic, it started working. Now I see the 3D estimated  position, 2D estimated position, and the local view output.

**Comment by chrisspen** [comment]
For a typical indoor environment, how many runs should it typically take before it converges?

I tried walking my laptop around my apartment a few times, to see how well it converges to a usable map, and I'm getting some strange results. My room layout is simply a kitchen and living room, connected by two openings, so I can walk in a circle in through the kitchen, back out into the living room, and then back into the kitchen.

After walking it in a circle about 10 times, it showed this:

![Screenshot from 2020-03-10 10-30-43](https://user-images.githubusercontent.com/116631/76324010-d29afb00-62bb-11ea-8ff3-88da234a8ded.png)

so clearly, it's figuring out it's going in a circle using only visual odometry, but it's getting a little confused, and mistakenly thinks it's gone in several different paths.

Also, its estimate seems to drift a lot. When I finished and sat my laptop down, with the camera facing a stationary wall, both the 2d and 3d views showed it was "walking off" in a straight line. A few minutes after I took the above screenshot, it then looked like this:

![Screenshot from 2020-03-10 10-33-02](https://user-images.githubusercontent.com/116631/76324275-273e7600-62bc-11ea-8d8c-d738b3ddaf75.png)

Is this normal? Is there anything I can do to prevent this, or is this just a limitation of the visual odometry node?

Also, what's the purpose of the third "Local View" window? It appears to be a mangled and pixelated version of the raw camera feed and looks like:

![Screenshot from 2020-03-10 10-31-07](https://user-images.githubusercontent.com/116631/76324436-610f7c80-62bc-11ea-8c07-dd578f8cd1c8.png)

Is it supposed to look like that or have I misconfigured something?

**Comment by sunt40** [comment]
I also have these problems like you ,still not solve.

**Comment by scott--** [comment]
Hi @chrisspen,

Your camera node is not providing the format that RatSLAM expects, it needs to be bgr8 or grayscale.

Visual odometry generally doesn't work as well as encoders. 

Finally, frame matching is done through comparing visual templates - pictures that have been converted to grayscale, and then down-sampled (pixelated), which is a fairly simple method that is not particularly robust. Generally in RatSLAM papers,  robots / cars used have followed their previous paths very closely when they revisit the same places.

**Comment by chrisspen** [comment]
Hi @scott--,

Thanks for the input.

As far as the camera format, is there a straight forward solution for that? I'm using the standard [usb_cam](http://wiki.ros.org/usb_cam) node, and it doesn't have either a bgr8 or grayscale mode. If I run this to check my camera output:

    rosrun image_view image_view image:=/camera/image _image_transport:=compressed _autosize:=true

it displays the camera output perfectly.

I'm using the [default](https://github.com/ros-drivers/usb_cam/blob/develop/launch/usb_cam-test.launch) launch file, which records in yuyv format.

**Comment by scott--** [comment]
It's hard to debug your setup from here - but here are some things that might help:
- Although I initially thought that your camera setup was not right, you are using the compressed transport, so I would expect the decompression (which happens in image_transport) to correctly convert to bgr8 anyway.
- Make sure you do not have vt_panoramic set to 1 (it should be 0), that causes the local view and visual odometry to expect panoramic images. 
- Try putting some breakpoints in the image_callback function in main_lv or main_vo. Check that the image format is as expected. It needs to either grayscale, or bgr8 (24 bits / pixel) at this stage.

**Comment by sunt40** [comment]
Hi, @chrisspen 
The following is mine,I think that is correct.
`Subscriptions: 
 * /usb_cam/image_raw/compressed [sensor_msgs/CompressedImage]`

**Comment by chrisspen** [comment]
@sunt40 Yeah, after I fixed the topic_root in my config, then the subscription began reporting the correct CompressedImage type.

The problem now is the system just doesn't work very well, and I'm trying to figure out if it's just the natural performance of the algorithm, or if I have something misconfigured. I'm not getting any errors, and the local view is showing an image (albeit as a double-image with pixelation). A big problem is there's substantial drift when there's no significant change in the video. The system thinks it's always cruising around even when sitting still.

I think I've gone as far as I can go, and since this project doesn't appear to be maintained anymore, it doesn't make sense to invest any more time. For the record, this is what was sort of working  for me.

You have to explicitly install a ton of undocumented dependencies that even the full desktop install doesn't install, otherwise the nodes silently fail and don't even report errors, which is incredibly annoying:

    sudo apt-get install -yq libirrlicht-dev libopencv-dev ros-melodic-tf ros-melodic-image-transport ros-melodic-compressed-image-transport ros-melodic-topic-tools ros-melodic-rqt-plot ros-melodic-usb-cam ros-melodic-rviz ros-melodic-image-view ros-melodic-compressed-image-transport ros-melodic-image-transport ros-melodic-rqt* python-pyqt5

I setup a catkin workspace as explained in the docs.

I then started a node to publish my webcam with the launch file:

    <launch>
      <node name="usb_cam" pkg="usb_cam" type="usb_cam_node" output="screen" >
        <param name="video_device" value="/dev/video0" />
        <param name="image_width" value="640" />
        <param name="image_height" value="480" />
        <param name="pixel_format" value="yuyv" />
        <param name="camera_frame_id" value="usb_cam" />
        <param name="io_method" value="mmap"/>
      </node>
      <node name="image_view" pkg="image_view" type="image_view" respawn="false" output="screen">
        <remap from="image" to="/usb_cam/image_raw"/>
        <param name="autosize" value="true" />
        <param name="image_transport" value="compressed" />
      </node>
    </launch>

which I launched with:

    roslaunch ratslam_ros usb_cam.launch

I then renamed the compressed topic so ratslam would use it by running:

    rosrun topic_tools relay /usb_cam/image_raw/compressed /usb_cam/camera/image/compressed

Finally, I created the launch file my_robot.launch:

    <launch>

        <machine name="local_alt" address="localhost" default="true" />
        
        <node name="RatSLAMLocalViewCells" pkg="ratslam_ros" type="ratslam_lv" args="$(find ratslam_ros)/config/config_my_robot.txt _image_transport:=compressed" cwd="node" required="true" />
        <node name="RatSLAMPoseCells" pkg="ratslam_ros" type="ratslam_pc" args="$(find ratslam_ros)/config/config_my_robot.txt _image_transport:=compressed" cwd="node" required="true" />
        <node name="RatSLAMExperienceMap" pkg="ratslam_ros" type="ratslam_em" args="$(find ratslam_ros)/config/config_my_robot.txt _image_transport:=compressed" cwd="node" required="true" />
        <node name="RatSLAMVisualOdometry" pkg="ratslam_ros" type="ratslam_vo" args="$(find ratslam_ros)/config/config_my_robot.txt _image_transport:=compressed" cwd="node" required="true" />
        
        
        <node pkg="rosbag" type="record" name="record" args="/my_robot/ExperienceMap/Map /my_robot/ExperienceMap/RobotPose /my_robot/LocalView/Template /my_robot/PoseCell/TopologicalAction -O ratslam_out.bag" />

    </launch>

and `config/config_my_robot.txt`, which is just a copy of `config/config_stlucia.txt` but with `topic_root=usb_cam`.

I then ran that with:

    roslaunch ratslam_ros my_robot.launch
