### ISSUE TITLE
easy way to run your C++ sample?

### ISSUE THREAD

**Issue by Thanh-Binh** [davidmball/ratslam#6]
I have successfully built ratslam and sample, but I am not sure what exactly needs for running/testing this sample off-line.
Do you have any dataset video (dataset_video_filename) and dataset csv (dataset_csv_filename)?

Best thanks

**Comment by davidmball** [comment]
The datasets for the C++ version are available from https://wiki.qut.edu.au/display/cyphy/RatSLAM+MATLAB .

**Comment by Thanh-Binh** [comment]
I have just tried to download them but the links failed. Could you please check it again?

I think ratslam need only video data. Why need your sample the 2nd dataset?
Thanks

**Comment by davidmball** [comment]
RatSLAM needs some self motion estimation. This can be generated from the video or from an odometry source. The axon dataset was generated with a robot so it has odometry as well. The st lucia dataset was generated only using a webcam so visual odometry was hacked in.

**Comment by Thanh-Binh** [comment]
Best thanks for your explaination.
It is fine to have a version running with/without odometery. It found that your sw does not use FFT for visual matching as written in your paper. Why?

**Comment by davidmball** [comment]
I'm not sure exactly what paper you are referring to or what visual matching you are referring to. If you are talking about the 'visual odometry' then it uses a very crude scanline matching. eg to estimate rotation it compares consecutive scanlines. If you are talking about the local view match then it uses visual templates, which are global feature vectors representing a view from a particular location. Full details are in our autonomous robotics paper from 2013, OpenRatSLAM.

**Comment by Thanh-Binh** [comment]
I think about the paper of M Milford, 2009
Persistent navigation and mapping using biological inspired SLam
Which used fft for object recognition and localization in ratslam!

**Comment by davidmball** [comment]
I think this goes beyond running the c++ sample. I'd suggest you contact the original author Michael Milford to discuss over email / phone.  http://staff.qut.edu.au/staff/milfordm/

**Comment by Thanh-Binh** [comment]
Thanks, I will contact him ...
