### ISSUE TITLE
Datasets for testing ratSlam

### ISSUE THREAD

**Issue by Thanh-Binh** [davidmball/ratslam#7]
I have just tried to download them at
https://wiki.qut.edu.au/display/cyphy/RatSLAM+MATLAB

but the links failed. 
Could you please upload any dataset into this repository?

Thanks

**Comment by davidmball** [comment]
I'm not at QUT anymore so it is hard. Note that I recommend the ROS version with associated bag files. The raw OpenCV C++ version hasn't been used in a while. 
Here are 2 files I found:
https://www.dropbox.com/s/dshskls3qv6bhpi/uqaxon5_0to4000.avi?dl=0
https://www.dropbox.com/s/uola387suz0b08k/uqaxon5_0to4000.txt?dl=0

**Comment by davidmball** [comment]
I've changed the default branch now to the ros version. Unless there is a specific reason I'd suggest using the ros version.
