### ISSUE TITLE
Linking ratslam_pc ratslam_em ~catkin_ws/devel/lib/libratslam.so: undefined reference to `cv::String::deallocate()'

### ISSUE THREAD

**Issue by PhilippeLC92** [davidmball/ratslam#8]
Hello,
I have an error during catkin_make: libratslam.so: undefined reference to `cv :: String :: deallocate () '. Could you help me solve this error?

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
ros kinetic

~/catkin_ws# catkin_make
Base path: /root/catkin_ws
Source space: /root/catkin_ws/src
Build space: /root/catkin_ws/build
Devel space: /root/catkin_ws/devel
Install space: /root/catkin_ws/install
####
####
-- Using CATKIN_DEVEL_PREFIX: /root/catkin_ws/devel
-- Using CMAKE_PREFIX_PATH: /root/catkin_ws/devel;/opt/ros/kinetic
-- This workspace overlays: /root/catkin_ws/devel;/opt/ros/kinetic
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /root/catkin_ws/build/test_results
-- Found gtest sources under '/usr/src/gtest': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.7.8
-- BUILD_SHARED_LIBS is on
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 1 packages in topological order:
-- ~~  - ratslam_ros
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin package: 'ratslam_ros'
-- ==> add_subdirectory(ratslam_ros)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- Found OpenCV: /opt/ros/kinetic (found version "3.3.1") 
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   serialization
-- IRRLICHT_INCLUDE_DIR = /usr/include
-- IRRLICHT_LIBRARY = /usr/lib/x86_64-linux-gnu/libIrrlicht.so
-- Found IRRLICHT: /usr/lib/x86_64-linux-gnu/libIrrlicht.so  
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so  
-- ratslam_ros: 5 messages, 0 services
-- Configuring done
-- Generating done
-- Build files have been written to: /root/catkin_ws/build
####
####
Scanning dependencies of target _ratslam_ros_generate_messages_check_deps_ViewTemplate
Scanning dependencies of target _ratslam_ros_generate_messages_check_deps_TopologicalNode
Scanning dependencies of target std_msgs_generate_messages_cpp
Scanning dependencies of target geometry_msgs_generate_messages_cpp
Scanning dependencies of target _ratslam_ros_generate_messages_check_deps_TopologicalEdge
Scanning dependencies of target _ratslam_ros_generate_messages_check_deps_TopologicalMap
Scanning dependencies of target ratslam
Scanning dependencies of target _ratslam_ros_generate_messages_check_deps_TopologicalAction
[  0%] Built target std_msgs_generate_messages_cpp
[  0%] Built target geometry_msgs_generate_messages_cpp
Scanning dependencies of target geometry_msgs_generate_messages_nodejs
Scanning dependencies of target std_msgs_generate_messages_nodejs
[  0%] Built target geometry_msgs_generate_messages_nodejs
[  0%] Built target std_msgs_generate_messages_nodejs
Scanning dependencies of target std_msgs_generate_messages_lisp
[  0%] Built target _ratslam_ros_generate_messages_check_deps_TopologicalMap
[  0%] Built target _ratslam_ros_generate_messages_check_deps_TopologicalEdge
Scanning dependencies of target geometry_msgs_generate_messages_lisp
[  0%] Built target _ratslam_ros_generate_messages_check_deps_TopologicalAction
[  0%] Built target _ratslam_ros_generate_messages_check_deps_ViewTemplate
[  0%] Built target _ratslam_ros_generate_messages_check_deps_TopologicalNode
[  0%] Built target std_msgs_generate_messages_lisp
Scanning dependencies of target geometry_msgs_generate_messages_py
Scanning dependencies of target std_msgs_generate_messages_eus
Scanning dependencies of target std_msgs_generate_messages_py
[  0%] Built target geometry_msgs_generate_messages_lisp
Scanning dependencies of target geometry_msgs_generate_messages_eus
Scanning dependencies of target ratslam_ros_generate_messages_cpp
Scanning dependencies of target ratslam_ros_generate_messages_nodejs
[  0%] Built target geometry_msgs_generate_messages_py
[  0%] Built target std_msgs_generate_messages_py
[  0%] Built target geometry_msgs_generate_messages_eus
Scanning dependencies of target ratslam_ros_generate_messages_lisp
[  2%] Building CXX object ratslam_ros/CMakeFiles/ratslam.dir/src/ratslam/experience_map.cpp.o
[  2%] Built target std_msgs_generate_messages_eus
[  5%] Building CXX object ratslam_ros/CMakeFiles/ratslam.dir/src/ratslam/posecell_network.cpp.o
[  7%] Generating C++ code from ratslam_ros/TopologicalNode.msg
[ 10%] Generating Lisp code from ratslam_ros/TopologicalNode.msg
[ 12%] Generating Javascript code from ratslam_ros/TopologicalNode.msg
Scanning dependencies of target ratslam_ros_generate_messages_eus
Scanning dependencies of target ratslam_ros_generate_messages_py
[ 15%] Building CXX object ratslam_ros/CMakeFiles/ratslam.dir/src/ratslam/local_view_match.cpp.o
[ 17%] Generating Python from MSG ratslam_ros/TopologicalNode
[ 20%] Generating EusLisp code from ratslam_ros/TopologicalNode.msg
[ 22%] Generating Javascript code from ratslam_ros/TopologicalMap.msg
[ 25%] Generating Lisp code from ratslam_ros/TopologicalMap.msg
[ 27%] Generating Python from MSG ratslam_ros/TopologicalMap
[ 30%] Generating EusLisp code from ratslam_ros/TopologicalMap.msg
[ 32%] Generating Lisp code from ratslam_ros/TopologicalAction.msg
[ 35%] Generating Javascript code from ratslam_ros/TopologicalAction.msg
[ 37%] Generating Python from MSG ratslam_ros/TopologicalAction
[ 40%] Generating EusLisp code from ratslam_ros/TopologicalAction.msg
[ 42%] Generating Lisp code from ratslam_ros/ViewTemplate.msg
[ 45%] Generating Javascript code from ratslam_ros/ViewTemplate.msg
[ 47%] Generating C++ code from ratslam_ros/TopologicalMap.msg
[ 50%] Generating Python from MSG ratslam_ros/ViewTemplate
[ 52%] Generating Lisp code from ratslam_ros/TopologicalEdge.msg
[ 55%] Generating EusLisp code from ratslam_ros/ViewTemplate.msg
[ 57%] Generating Javascript code from ratslam_ros/TopologicalEdge.msg
[ 60%] Generating Python from MSG ratslam_ros/TopologicalEdge
[ 60%] Built target ratslam_ros_generate_messages_lisp
[ 62%] Generating EusLisp manifest code for ratslam_ros
[ 65%] Generating EusLisp code from ratslam_ros/TopologicalEdge.msg
[ 65%] Built target ratslam_ros_generate_messages_nodejs
[ 67%] Building CXX object ratslam_ros/CMakeFiles/ratslam.dir/src/ratslam/visual_odometry.cpp.o
[ 70%] Generating Python msg __init__.py for ratslam_ros
[ 72%] Generating C++ code from ratslam_ros/TopologicalAction.msg
[ 75%] Generating C++ code from ratslam_ros/ViewTemplate.msg
[ 75%] Built target ratslam_ros_generate_messages_py
[ 77%] Generating C++ code from ratslam_ros/TopologicalEdge.msg
[ 77%] Built target ratslam_ros_generate_messages_cpp
[ 77%] Built target ratslam_ros_generate_messages_eus
Scanning dependencies of target ratslam_ros_generate_messages
[ 77%] Built target ratslam_ros_generate_messages
[ 80%] Linking CXX shared library /root/catkin_ws/devel/lib/libratslam.so
[ 80%] Built target ratslam
Scanning dependencies of target ratslam_pc
Scanning dependencies of target ratslam_lv
Scanning dependencies of target ratslam_em
Scanning dependencies of target ratslam_vo
[ 82%] Building CXX object ratslam_ros/CMakeFiles/ratslam_pc.dir/src/main_pc.cpp.o
[ 85%] Building CXX object ratslam_ros/CMakeFiles/ratslam_em.dir/src/main_em.cpp.o
[ 87%] Building CXX object ratslam_ros/CMakeFiles/ratslam_vo.dir/src/main_vo.cpp.o
[ 90%] Building CXX object ratslam_ros/CMakeFiles/ratslam_lv.dir/src/main_lv.cpp.o
[ 92%] Linking CXX executable /root/catkin_ws/devel/lib/ratslam_ros/ratslam_vo
[ 95%] Linking CXX executable /root/catkin_ws/devel/lib/ratslam_ros/ratslam_lv
[ 97%] Linking CXX executable /root/catkin_ws/devel/lib/ratslam_ros/ratslam_pc
[ 97%] Built target ratslam_vo
[ 97%] Built target ratslam_lv
/root/catkin_ws/devel/lib/libratslam.so: undefined reference to `cv::String::deallocate()'
collect2: error: ld returned 1 exit status
ratslam_ros/CMakeFiles/ratslam_pc.dir/build.make:132: recipe for target '/root/catkin_ws/devel/lib/ratslam_ros/ratslam_pc' failed
make[2]: *** [/root/catkin_ws/devel/lib/ratslam_ros/ratslam_pc] Error 1
CMakeFiles/Makefile2:410: recipe for target 'ratslam_ros/CMakeFiles/ratslam_pc.dir/all' failed
make[1]: *** [ratslam_ros/CMakeFiles/ratslam_pc.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Linking CXX executable /root/catkin_ws/devel/lib/ratslam_ros/ratslam_em
/root/catkin_ws/devel/lib/libratslam.so: undefined reference to `cv::String::deallocate()'
collect2: error: ld returned 1 exit status
ratslam_ros/CMakeFiles/ratslam_em.dir/build.make:132: recipe for target '/root/catkin_ws/devel/lib/ratslam_ros/ratslam_em' failed
make[2]: *** [/root/catkin_ws/devel/lib/ratslam_ros/ratslam_em] Error 1
CMakeFiles/Makefile2:1504: recipe for target 'ratslam_ros/CMakeFiles/ratslam_em.dir/all' failed
make[1]: *** [ratslam_ros/CMakeFiles/ratslam_em.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j8 -l8" failed

**Comment by davidmball** [comment]
Sorry for taking a while to respond. Unfortunately, I can't immediately see what the problem is. I'd need to look into it in more detail. However, I just wanted to let you know that I may not have time for the next two weeks to look into this.
If I had to guess I would say that the opencv library has changed versions and the ratlsam code isn't including the right header or linking against the full set of libraries.

**Comment by agnostic-apollo** [comment]
yes this is an opencv version conflict problem, ros comes with opencv3 now(using kinetic), and cmake tries to find the latest version available on the system and some functions are deprecated and wont work with opencv3..
to fix this first make sure you have opencv2 installed on your system..
on my ubuntu 16.04 running the command below installed it, you can check /usr/include/opencv2 to confirm..
sudo apt-get install libopencv-dev

secondly in ratslam_ros/CMakeLists.txt 
change line 12, find_package(OpenCV) to find_package(OpenCV 2)
this should force ros to use opencv2 to compile the code

@davidmball i think you should make a commit too
thanks

**Comment by davidmball** [comment]
@agnostic-apollo Thanks. I'll check it out later.

**Comment by agnostic-apollo** [comment]
you are welcome.

**Comment by PhilippeLC92** [comment]
Hello,
Many thanks : catkin_make ended successfully
Now I try 

catkin_make
.../...
Scanning dependencies of target ratslam_pc
Scanning dependencies of target ratslam_lv
Scanning dependencies of target ratslam_vo
Scanning dependencies of target ratslam_em
[ 82%] Building CXX object ratslam_ros/CMakeFiles/ratslam_lv.dir/src/main_lv.cpp.o
[ 85%] Building CXX object ratslam_ros/CMakeFiles/ratslam_pc.dir/src/main_pc.cpp.o
[ 87%] Building CXX object ratslam_ros/CMakeFiles/ratslam_vo.dir/src/main_vo.cpp.o
[ 90%] Building CXX object ratslam_ros/CMakeFiles/ratslam_em.dir/src/main_em.cpp.o
[ 92%] Linking CXX executable /root/catkin_ws/devel/lib/ratslam_ros/ratslam_vo
[ 95%] Linking CXX executable /root/catkin_ws/devel/lib/ratslam_ros/ratslam_lv
[ 95%] Built target ratslam_lv
[ 95%] Built target ratslam_vo
[ 97%] Linking CXX executable /root/catkin_ws/devel/lib/ratslam_ros/ratslam_pc
[ 97%] Built target ratslam_pc
[100%] Linking CXX executable /root/catkin_ws/devel/lib/ratslam_ros/ratslam_em
[100%] Built target ratslam_em

**Comment by PhilippeLC92** [comment]
Now I'm trying to run : roslaunch cozmo_driver ratslam.launch 
from https://github.com/OTL/cozmo_driver
but not yet working.

**Comment by agnostic-apollo** [comment]
@davidmball whats your active email? the ones on your website are inactive. 
thanks

**Comment by davidmball** [comment]
Thank you for heads up about the inactive emails. I'm in the process of fixing those. but it will take time.

**Comment by agnostic-apollo** [comment]
welcome
